[weekday]
"<b>Weekly Events</b>" = "Tues 8:30 PM"
"<b>Gemara Shiur</b><div class=\"fs-sm\">Avoda Zara: 2nd Perek</div>" = "Thurs 8:30 PM"

[shabbat]
"<b>Minḥa</b> (Korbanot)" = "6:45 PM"
"<b>Nefesh Ha'chaim</b>" = "8:15 AM"
"<b>Shaḥarit</b><div class=\"fs-sm\">Followed by Kiddush</div>" = "9:00 AM"
"<b>Boys Halacha</b>" = "4:30 PM"
"<b>Ladies Halacha</b>" = "5:30 PM"
"<b>Mens Class</b>" = "6:30 PM"
"<b>Minḥa</b> (סעודת שלישית)" = "7:30 PM"
"<b>Arvit Motzash</b>" = "8:35 PM"
