[weekday]
"<b>Weekly Events</b>" = "Tues 8:30 PM"
"<b>Gemara Shiur</b><div class=\"fs-sm\">Avoda Zara: 2nd Perek</div>" = "Thurs 8:30 PM"

[shabbat]
"<b>Candle Lighting</b><div class=\"fs-sm\">(both nights)</div>" = "7:51 PM"
"<b>Minḥa Erev Chag</b>" = "7:30 PM"
"<b>Tikkun Starts</b>" = "11:00 PM"
"<b>Shaḥarit 1st Day</b>" = "4:45 AM"
"<b>Second Reading</b><div class=\"fs-sm\">Ladies & Kids Ice Cream Party</div>" = "5:30 PM"
"<b>Minḥa</b><div class=\"fs-sm\">Erev Shabbat</div>" = "7:15 PM"
"<b>Nefesh Ha'chaim</b>" = "8:15 AM"
"<b>Shaḥarit</b><div class=\"fs-sm\">Followed by Kiddush</div>" = "9:00 AM"
"<b>Boys Halacha</b>" = "4:30 PM"
"<b>Ladies Halacha</b>" = "5:30 PM"
"<b>Pirkei Avot Class</b>" = "6:30 PM"
"<b>Minḥa</b><div class=\"fs-sm\">Seuda Shlishit</div>" = "7:30 PM"
