[weekday]
<b>1<sup>st</sup> Shacharit</b> (Hodu) = 6:55/7:00 AM (Mon-Fri)
<b>2<sup>nd</sup> Shacharit</b> (Hodu) = 8:15 AM
<b>Mincha & Arvit</b> = 4:55 PM
<b>2<sup>nd</sup> Arvit</b> = 9:30 PM

[shabbat]
<b>Erev Shabbat Tefilot</b> + Learning = 4:57 PM
<b>Shacharit</b> (+ Kiddush & Learning) = 8:30 AM
<b>Mincha</b> = 4:30 PM
<b>Arvit</b> = 6:00 PM

[sedarim]
<b>Early Morning</b> = Mon-Fri, 6:15 AM
<b>Morning</b> (+ Avrechim) = Sun-Fri, 7:45 AM
<b>Night</b> (+ Food) = Sun-Thu, 8:20 PM
#<b>Shabbat</b> = 4:00 PM

[shiurim]
<b>Kinyan Hamasechta - Megila</b><br>w/ R' Yonah Nisanov=Mon-Fri, 6:15 AM<br>Mon-Thu, 9:00 PM
<b>Tefila</b> w/ R' Yonah Nisanov=Mon-Thu, 8:30 PM
<b>Hilchot Shabbat</b> w/ R' Emanuel Aminov=Sun-Thu, 8:30 PM
<b>Morning Halachot & Sha'ar Habitachon</b><br>w/ R' Aharon Sulimanov=Mon & Wed,<br>8:30 PM
